#!/bin/bash
set -e

login_user=`/usr/bin/stat -f%Su /dev/console`
rilinic_app_root="${DSTROOT}/rilinic.app"
rilinic_executable="${rilinic_app_root}/Contents/MacOS/rilinic"
rime_shared_data_path="${rilinic_app_root}/Contents/SharedSupport"

/usr/bin/sudo -u "${login_user}" /usr/bin/killall rilinic > /dev/null || true

"${rilinic_executable}" --register-input-source

if [ -z "${RIME_NO_PREBUILD}" ]; then
    pushd "${rime_shared_data_path}" > /dev/null
    "${rilinic_executable}" --build
    popd > /dev/null
fi && (
    /usr/bin/sudo -u "${login_user}" "${rilinic_executable}" --enable-input-source
    /usr/bin/sudo -u "${login_user}" "${rilinic_executable}" --select-input-source
)
